services:
  - type: web
    name: nk-backend
    runtime: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: WORKSPACES_PATH
        value: "workspaces"
    plan: starter
    region: oregon